supercoding-3st-project/food-place-BE

- build.gradle
- src/main/java/com/github/foodplacebe/config/JpaConfig.java
- src/main/java/com/github/foodplacebe/repository/commentFavorite/CommentFavorite.java
- src/main/java/com/github/foodplacebe/repository/commentFavorite/CommentFavoriteJpa.java
- src/main/java/com/github/foodplacebe/repository/comments/Comments.java
- src/main/java/com/github/foodplacebe/repository/comments/CommentsJpa.java
- src/main/java/com/github/foodplacebe/repository/postFavorite/PostFavorite.java
- src/main/java/com/github/foodplacebe/repository/postFavorite/PostFavoriteJpa.java
- src/main/java/com/github/foodplacebe/repository/postPhotos/PostPhotos.java
- src/main/java/com/github/foodplacebe/repository/postPhotos/PostPhotosJpa.java
- src/main/java/com/github/foodplacebe/repository/posts/Posts.java
- src/main/java/com/github/foodplacebe/repository/posts/PostsJpa.java
- src/main/java/com/github/foodplacebe/repository/users/UserEntity.java
- src/main/resources/application-local.yaml
- src/main/resources/application-prod.yaml
- src/main/resources/application.yml
> JPA Setting

- src/main/java/com/github/foodplacebe/config/security/SecurityConfig.java
> test 로직 permitAll 에 추가

- src/main/java/com/github/foodplacebe/config/JpaConfig.java
- src/main/java/com/github/foodplacebe/repository/users/UserEntity.java
> Feat hansol

- src/main/java/com/github/foodplacebe/repository/userDetails/CustomUserDetails.java
- src/main/java/com/github/foodplacebe/repository/users/UserEntity.java
- src/main/java/com/github/foodplacebe/service/authAccount/AccountLockService.java
- src/main/java/com/github/foodplacebe/service/authAccount/SignUpLoginService.java
- src/main/java/com/github/foodplacebe/service/authAccount/oauth/SocialSettingService.java
- src/main/java/com/github/foodplacebe/service/authAccount/oauth/SocialSignUpService.java
- src/main/java/com/github/foodplacebe/service/mappers/UserMapper.java
- src/main/java/com/github/foodplacebe/service/security/CustomUserDetailsService.java
- src/main/java/com/github/foodplacebe/web/controller/authAccount/SocialController.java
- src/main/java/com/github/foodplacebe/web/dto/account/SocialAccountDto.java
- 유저 롤이 없어서 임시생성 계정 못가져오던 오류 수정 Resolves issue #9
> fix: 소셜 로그인 (카카오)

- src/main/java/com/github/foodplacebe/repository/postFavorite/PostFavorite.java
- src/main/java/com/github/foodplacebe/repository/postFavorite/PostFavoriteJpa.java
- src/main/java/com/github/foodplacebe/repository/posts/Posts.java
- src/main/java/com/github/foodplacebe/service/exceptions/NotFoundException.java
- src/main/java/com/github/foodplacebe/service/hansolService/PostDetailService.java
- src/main/java/com/github/foodplacebe/service/mappers/PostMapper.java
- src/main/java/com/github/foodplacebe/web/controller/hansol/PostDetailController.java
- src/main/java/com/github/foodplacebe/web/dto/hansolDto/PostDetailResponse.java
- src/main/java/com/github/foodplacebe/web/dto/hansolDto/PostPhotoDto.java
feat-getPostDetail and pushFavorite
>  feat-getPostDetail and pushFavorite

- src/main/java/com/github/foodplacebe/service/hansolService/PostDetailService.java
- src/main/java/com/github/foodplacebe/web/controller/hansol/PostDetailController.java
feat: post-favorite-status(좋아요 등록 여부 확인 로직 추가)
> feat: post-favorite-status(ì¡좋아요 등록 여부 ì확인 로직 추가)

- src/main/java/com/github/foodplacebe/config/security/oauth/client/KakaoApiClient.java
- src/main/java/com/github/foodplacebe/repository/comments/Comments.java
- src/main/java/com/github/foodplacebe/repository/posts/Posts.java
- src/main/java/com/github/foodplacebe/service/authAccount/SignUpLoginService.java
- src/main/java/com/github/foodplacebe/service/authAccount/oauth/SocialSettingService.java
- src/main/java/com/github/foodplacebe/service/authAccount/oauth/SocialSignUpService.java
- src/main/java/com/github/foodplacebe/service/authAccount/test/TestService.java
- src/main/java/com/github/foodplacebe/web/controller/authAccount/SignUpLoginController.java
- src/main/java/com/github/foodplacebe/web/controller/authAccount/SocialController.java
- src/main/java/com/github/foodplacebe/web/controller/authAccount/test/TestController.java
- src/main/java/com/github/foodplacebe/web/controller/authAccount/test/TestDto.java
- src/main/java/com/github/foodplacebe/web/filters/JwtFilter.java
- 가입, 수정 진행중 사용자가 그냥 종료했을경우 반영 #9
> fix: 소셜로그인 일부 수정

- src/main/java/com/github/foodplacebe/repository/posts/PostsJpa.java
- src/main/java/com/github/foodplacebe/service/PostsService/PostsMapper.java
- src/main/java/com/github/foodplacebe/service/PostsService/PostsService.java
- src/main/java/com/github/foodplacebe/web/controller/Posts/PostsController.java
- src/main/java/com/github/foodplacebe/web/dto/postDto/PostPhotosDto.java
- src/main/java/com/github/foodplacebe/web/dto/postDto/PostsDto.java
> Feature jiyun

- src/main/java/com/github/foodplacebe/service/authAccount/SignUpLoginService.java
- src/main/java/com/github/foodplacebe/service/authAccount/oauth/SocialSignUpService.java
> feat: 입력한 닉네임이 30자 초과일때 예외 발생

- src/main/java/com/github/foodplacebe/repository/commentFavorite/CommentFavoriteJpa.java
- src/main/java/com/github/foodplacebe/repository/comments/Comments.java
- src/main/java/com/github/foodplacebe/repository/comments/CommentsJpa.java
- src/main/java/com/github/foodplacebe/service/comment/Comment2Service.java
- src/main/java/com/github/foodplacebe/web/controller/comment/Comment2Controller.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentCreationDTO.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentModifyDTO.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentResponseDTO.java
- 댓글 등록/수정/삭제/조회 기능
- 댓글 좋아요 기능
> feat: 댓글 관리 기능 추가

- src/main/java/com/github/foodplacebe/repository/posts/PostsJpa.java
- src/main/java/com/github/foodplacebe/repository/users/UserEntity.java
- src/main/java/com/github/foodplacebe/repository/users/UserJpa.java
- src/main/java/com/github/foodplacebe/service/PostsService/PostsService.java
- src/main/java/com/github/foodplacebe/service/hansolService/MyPageService.java
- src/main/java/com/github/foodplacebe/service/hansolService/PostService.java
- src/main/java/com/github/foodplacebe/web/controller/Posts/PostsController.java
- src/main/java/com/github/foodplacebe/web/controller/hansol/CommentController.java
- src/main/java/com/github/foodplacebe/web/controller/hansol/MyPageController.java
- src/main/java/com/github/foodplacebe/web/controller/hansol/PostController.java
- src/main/java/com/github/foodplacebe/web/dto/hansolDto/MyInfoResponse.java
> feat: findRelatedPost 

- src/main/java/com/github/foodplacebe/config/security/SecurityConfig.java
- src/main/java/com/github/foodplacebe/service/PostsService/regPostService.java
- src/main/java/com/github/foodplacebe/service/hansolService/PostServiceHansol.java
- src/main/java/com/github/foodplacebe/web/controller/hansol/PostControllerHansol.java
- src/main/resources/application.yaml
> fix: s3 setting fix

- src/main/java/com/github/foodplacebe/web/controller/HealthCheckController.java
> fix: add health controller

- src/main/java/com/github/foodplacebe/service/PostsService/SearchPostService.java
검색기능 실행할 때 반환 데이터 값 리스트가 아닌 오브젝트로 반환되게 코드 수정해서 올려요!
> feat: 검색기능(반환 데이터값 수정)

- src/main/java/com/github/foodplacebe/service/comment/Comment2Service.java
- src/main/java/com/github/foodplacebe/web/controller/comment/Comment2Controller.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentCreationDTO.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentModifyDTO.java
- API 결과 값을 ResponseDTO로 통일
- 댓글 입력 & 수정시에 user_id를 입력하지 않도록 수정
> fix: 댓글 관리 수정

- src/main/java/com/github/foodplacebe/service/comment/Comment2Service.java
- src/main/java/com/github/foodplacebe/web/controller/HealthCheckController.java
- src/main/java/com/github/foodplacebe/web/controller/comment/Comment2Controller.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentResponseDTO.java
> Prac hansol

- src/main/java/com/github/foodplacebe/repository/users/UserEntity.java
- src/main/java/com/github/foodplacebe/service/PostsService/PostPhotosService.java
- src/main/java/com/github/foodplacebe/service/authAccount/AccountService.java
- src/main/java/com/github/foodplacebe/web/controller/authAccount/AccountController.java
- src/main/java/com/github/foodplacebe/web/dto/account/UpdateMyInfoRequest.java
- src/main/java/com/github/foodplacebe/web/dto/account/UpdatePasswordRequest.java
> feat: 회원정보 로직 구현

- src/main/java/com/github/foodplacebe/service/authAccount/AccountService.java
- src/main/java/com/github/foodplacebe/web/dto/account/UpdateMyInfoRequest.java
> fix: 회원정보 수정 기능 수정

- src/main/java/com/github/foodplacebe/repository/commentFavorite/CommentFavoriteJpa.java
- src/main/java/com/github/foodplacebe/service/comment/Comment2Service.java
- src/main/java/com/github/foodplacebe/web/controller/comment/Comment2Controller.java
- src/main/java/com/github/foodplacebe/web/dto/comment/CommentResponse_AuthDTO.java
- 댓글 조회에서 로그인한 유저가 해당 댓글의 좋아요를 눌렀는지에 대한 여부도 포함
( Token 입력시만 위와 같이 조회하도록 수정 )
- request url 마지막에 "/" 빼도록 수정
> fix: 댓글 조회 기능 수정

- src/main/java/com/github/foodplacebe/config/security/SecurityConfig.java
fix: Security Config 에 account로직 전부 추가
> fix: Security Config 에 account로직 전부 추가
